In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.model_selection import train_test_split, KFold,StratifiedKFold, LeaveOneOut, ShuffleSplit, cross_val_score

In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

In [4]:
df = sns.load_dataset('penguins')

In [5]:
df.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female  
3          NaN     NaN  
4       3450.0  Female

In [6]:
df.isna().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [7]:
df.shape

(344, 7)

In [8]:
df['sex'].value_counts()

sex
Male      168
Female    165
Name: count, dtype: int64

In [9]:
df['sex'].fillna('Male',inplace=True)

In [10]:
df.isna().sum()

species              0
island               0
bill_length_mm       2
bill_depth_mm        2
flipper_length_mm    2
body_mass_g          2
sex                  0
dtype: int64

In [14]:
df.dropna(inplace=True)

In [15]:
df.isna().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [16]:
x = df.drop(columns='species')

In [17]:
y = df['species']

In [18]:
x = pd.get_dummies(x)

In [19]:
x

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
0              39.1           18.7              181.0       3750.0   
1              39.5           17.4              186.0       3800.0   
2              40.3           18.0              195.0       3250.0   
4              36.7           19.3              193.0       3450.0   
5              39.3           20.6              190.0       3650.0   
..              ...            ...                ...          ...   
338            47.2           13.7              214.0       4925.0   
340            46.8           14.3              215.0       4850.0   
341            50.4           15.7              222.0       5750.0   
342            45.2           14.8              212.0       5200.0   
343            49.9           16.1              213.0       5400.0   

     island_Biscoe  island_Dream  island_Torgersen  sex_Female  sex_Male  
0            False         False              True       False      True  
1            False         False              True        True     False  
2            False         False              True        True     False  
4            False         False              True        True     False  
5            False         False              True       False      True  
..             ...           ...               ...         ...       ...  
338           True         False             False        True     False  
340           True         False             False        True     False  
341           True         False             False       False      True  
342           True         False             False        True     False  
343           True         False             False       False      True  

[342 rows x 9 columns]

In [21]:
del x['sex_Male']

In [39]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=12,stratify=y)

In [40]:
model = LogisticRegression()
model.fit(x_train,y_train)

C:\Users\lohit\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [41]:
pred = model.predict(x_test)

In [42]:
accuracy_score(y_test,pred)

0.9855072463768116

In [43]:
kfold = KFold(8)
model = LogisticRegression()
score = cross_val_score(estimator=model,X = x, y=y ,cv=kfold)

C:\Users\lohit\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\lohit\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

In [44]:
score

array([0.93023256, 1.        , 1.        , 0.97674419, 1.        ,
       0.97674419, 1.        , 1.        ])

In [45]:
score.mean()

0.9854651162790697

In [46]:
score.min()

0.9302325581395349

In [49]:
import warnings
warnings.filterwarnings('ignore')

In [50]:
stfkfold = StratifiedKFold(8)
scores = cross_val_score(estimator=model,X=x,y=y,cv = stfkfold)
scores

array([0.93023256, 0.97674419, 1.        , 1.        , 1.        ,
       1.        , 1.        , 0.97619048])

In [48]:
scores.mean()

0.9853959025470653

In [51]:
LOO = LeaveOneOut()
scores = cross_val_score(estimator=model,X=x,y=y,cv= LOO)
scores

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [52]:
score.mean()

0.9854651162790697

In [55]:
sspt = ShuffleSplit(n_splits=15,test_size=0.15)
score= cross_val_score(estimator=model,X=x,y=y,cv=sspt)
score


array([0.98076923, 1.        , 1.        , 1.        , 1.        ,
       1.        , 0.96153846, 0.96153846, 0.96153846, 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ])

In [56]:
score.mean()

0.991025641025641

In [57]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

      Adelie       0.97      1.00      0.98        30
   Chinstrap       1.00      0.93      0.96        14
      Gentoo       1.00      1.00      1.00        25

    accuracy                           0.99        69
   macro avg       0.99      0.98      0.98        69
weighted avg       0.99      0.99      0.99        69

